---
title: "OIA"
author: "Tom Saunders"
output: html_document
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), '/docs/index.html')) })
---

```{r, warning=FALSE, message=FALSE}
library(readxl)
library(readr)
library(lubridate)
library(dplyr)
library(forcats)
library(ggplot2)
```

```{r, message=FALSE}
# Data naming conventions appear to change so read in whatever excel file is in the `data` directory.

file_path = dir("data/", pattern = '\\.xlsx$', full.names = TRUE)

oia <- read_excel(file_path,
                  col_types = c("numeric", "text", "text", "text", 
                                "guess", "numeric", "numeric", "numeric", 
                                "numeric", "numeric", "numeric", "numeric",
                                "numeric", "numeric", "numeric", "numeric",
                                "numeric", "numeric", "numeric"))
# Select relevant columns

oia <- oia |> 
  select(c(1:7, 9:10, 12, 14, 16, 19))
```

```{r}
# Change column names, convert `survey_end` to date.

names(oia) <- c("org", "type", "agency", "agency_pref", 
                "survey_end", "oia_num", "oia_within_time", 
                "oia_pub", "oia_ext", "oia_tran", "oia_ref", 
                "ombud_complaints", "ombud_decisions")
```

```{r, message=FALSE}
# Data contains duplicated entries for 2016 and 2017 in an apparent attempt to make it easier to compare the first two collection periods (12 months) with the other collection periods (6 months). This effectively doubles the OIA request numbers for these periods so the 'total' from each of these periods needs to be removed, leaving the total split evenly between the two 6 month periods. 

remove <- oia |> 
  filter(type != "NA" & survey_end %in% c("2016-06-30", "2017-06-30")) |> 
  group_by(agency, survey_end) |>
  filter(oia_num == max(oia_num)) 

oia <- anti_join(oia, remove)
```

```{r}
# Remove rows where OrgID (org) is 0 as these rows appear to again be totals based on Agency Type.

oia <- oia |> 
  filter(org != 0)
```

```{r}
# For each agency, get total requests, proportion handled within statutory timeframe, and proportions of request extensions, transfers, refusals, ombudsman complaints, and ombudsman decisions from those complaints.

agency_totals <- oia |> 
  group_by(agency) |> 
  summarise(
    requests = sum(oia_num, na.rm = TRUE),
    within_time = sum(oia_within_time,  na.rm = TRUE) / requests,
    extensions = sum(oia_ext, na.rm = TRUE) / sum(oia_num, na.rm = TRUE),
    transfers = sum(oia_tran, na.rm = TRUE) / sum(oia_num, na.rm = TRUE),
    refusals = sum(oia_ref, na.rm = TRUE) / sum(oia_num, na.rm = TRUE),
    ombud_com = sum(ombud_complaints, na.rm = TRUE) / sum(oia_num, na.rm = TRUE),
    ombud_dec = sum(ombud_decisions, na.rm = TRUE) / sum(ombud_complaints, na.rm = TRUE)) |> 
  arrange(desc(requests))

top5 <- agency_totals |> slice_head(n = 5) 
```


```{r}
# Pull out year from date column.

oia$survey_end <- ymd(oia$survey_end)
oia$year <- as_factor(year(oia$survey_end))
```

```{r}
# Requests (and timeframe compliance) over time for busiest agencies.

trend <- oia |> 
  filter(agency %in% top5$agency) |> 
  group_by(agency,year) |> 
  summarise(
    total_oia = sum(oia_num, na.rm = TRUE),
    within_time = sum(oia_within_time, na.rm = TRUE) / total_oia,
  ) |> 
  ungroup() |>  
  mutate(agency = fct_reorder(agency, within_time, tail, n = 1, .desc = TRUE)) # sorts agency by final value on timeseries for legend readability

ggplot(trend, aes(x = year, y = within_time, group = agency, colour = agency)) +
  geom_line() +
  theme_classic() +
  labs(title = "OIA requests handled within statutory timeframe by year",
       colour = "Agency") +
  ylab("") +
  scale_y_continuous(labels = scales::percent) 

```

```{r}
# Look at trend of requests over time for NZ Police. Are pre-2019 numbers accurate?

oia |> 
  filter(agency == "New Zealand Police") |> 
  group_by(year) |> 
  tally(oia_num) |> 
  ggplot(aes(x = year, y = n)) +
  geom_col() +
  theme_classic()
```






